// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeQVzIdQ_EiqjBZkDZjOO9XAhLZNi6ShA',
    appId: '1:1033460573900:web:4d767cfd38fd2bfddec469',
    messagingSenderId: '1033460573900',
    projectId: 'test-a5a97',
    authDomain: 'test-a5a97.firebaseapp.com',
    databaseURL: 'https://test-a5a97-default-rtdb.firebaseio.com',
    storageBucket: 'test-a5a97.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVrz1tvwVX1B86uX7B7P5ElZBuQ9cfBmg',
    appId: '1:1033460573900:android:a4978ab45d11fc42dec469',
    messagingSenderId: '1033460573900',
    projectId: 'test-a5a97',
    databaseURL: 'https://test-a5a97-default-rtdb.firebaseio.com',
    storageBucket: 'test-a5a97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ7spPjJSnoMmO3sMVd2ZZtgZxNWaM42Q',
    appId: '1:1033460573900:ios:a25cd263aa04882bdec469',
    messagingSenderId: '1033460573900',
    projectId: 'test-a5a97',
    databaseURL: 'https://test-a5a97-default-rtdb.firebaseio.com',
    storageBucket: 'test-a5a97.appspot.com',
    iosBundleId: 'com.example.mealsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ7spPjJSnoMmO3sMVd2ZZtgZxNWaM42Q',
    appId: '1:1033460573900:ios:a25cd263aa04882bdec469',
    messagingSenderId: '1033460573900',
    projectId: 'test-a5a97',
    databaseURL: 'https://test-a5a97-default-rtdb.firebaseio.com',
    storageBucket: 'test-a5a97.appspot.com',
    iosBundleId: 'com.example.mealsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDeQVzIdQ_EiqjBZkDZjOO9XAhLZNi6ShA',
    appId: '1:1033460573900:web:564b7b08ffe427b2dec469',
    messagingSenderId: '1033460573900',
    projectId: 'test-a5a97',
    authDomain: 'test-a5a97.firebaseapp.com',
    databaseURL: 'https://test-a5a97-default-rtdb.firebaseio.com',
    storageBucket: 'test-a5a97.appspot.com',
  );
}
